# Generated from verified database schema.
SCHEMA = {'broker_account_state': {'bool': ['trade_allowed', 'connection_healthy'],
                          'columns': ['backend',
                                      'account_id',
                                      'snapshot_id',
                                      'observed_at',
                                      'broker_name',
                                      'environment',
                                      'currency',
                                      'balance',
                                      'equity',
                                      'floating_profit',
                                      'margin',
                                      'margin_free',
                                      'margin_level',
                                      'leverage',
                                      'trade_allowed',
                                      'connection_healthy',
                                      'metadata'],
                          'json': ['metadata'],
                          'uuid': []},
 'broker_accounts': {'bool': ['enabled'],
                     'columns': ['backend',
                                 'account_id',
                                 'broker_name',
                                 'environment',
                                 'enabled',
                                 'metadata',
                                 'updated_at'],
                     'json': ['metadata'],
                     'uuid': []},
 'broker_order_events': {'bool': ['accepted'],
                         'columns': ['id',
                                     'observed_at',
                                     'backend',
                                     'account_id',
                                     'signal_key',
                                     'broker_order_id',
                                     'event_type',
                                     'accepted',
                                     'code',
                                     'message',
                                     'payload'],
                         'json': ['payload'],
                         'uuid': []},
 'broker_position_state': {'bool': [],
                           'columns': ['backend',
                                       'account_id',
                                       'position_id',
                                       'snapshot_id',
                                       'observed_at',
                                       'symbol',
                                       'side',
                                       'volume',
                                       'open_price',
                                       'current_price',
                                       'sl',
                                       'tp',
                                       'profit',
                                       'swap',
                                       'magic',
                                       'comment',
                                       'opened_at',
                                       'metadata'],
                           'json': ['metadata'],
                           'uuid': []},
 'currency_macro_state': {'bool': [],
                          'columns': ['id',
                                      'currency',
                                      'observed_at',
                                      'rate_score',
                                      'central_bank_score',
                                      'inflation_score',
                                      'growth_score',
                                      'labour_score',
                                      'yield_score',
                                      'risk_score',
                                      'positioning_score',
                                      'macro_score',
                                      'coverage',
                                      'freshness_seconds',
                                      'evidence'],
                          'json': ['evidence'],
                          'uuid': []},
 'currency_strength': {'bool': [],
                       'columns': ['id',
                                   'currency',
                                   'observed_at',
                                   'strength_15m',
                                   'strength_1h',
                                   'strength_4h',
                                   'strength_1d',
                                   'combined_strength',
                                   'coverage'],
                       'json': [],
                       'uuid': []},
 'data_quality_snapshots': {'bool': ['stale', 'valid'],
                            'columns': ['id',
                                        'run_id',
                                        'symbol',
                                        'observed_at',
                                        'record_count',
                                        'duplicate_count',
                                        'non_monotonic_count',
                                        'stale',
                                        'spread_ratio',
                                        'valid',
                                        'issues',
                                        'created_at'],
                            'json': ['issues'],
                            'uuid': []},
 'execution_control': {'bool': ['new_orders_enabled',
                                'emergency_stop',
                                'close_all_requested'],
                       'columns': ['control_key',
                                   'execution_mode',
                                   'new_orders_enabled',
                                   'emergency_stop',
                                   'close_all_requested',
                                   'version',
                                   'updated_at',
                                   'metadata'],
                       'json': ['metadata'],
                       'uuid': []},
 'fx_symbols': {'bool': ['active'],
                'columns': ['symbol',
                            'base_currency',
                            'quote_currency',
                            'pip_size',
                            'tier',
                            'active',
                            'created_at'],
                'json': [],
                'uuid': []},
 'liquidity_levels': {'bool': ['active'],
                      'columns': ['id',
                                  'symbol',
                                  'timeframe',
                                  'observed_at',
                                  'level',
                                  'level_type',
                                  'strength',
                                  'touch_count',
                                  'active',
                                  'metadata'],
                      'json': ['metadata'],
                      'uuid': []},
 'market_structure': {'bool': ['bos', 'choch', 'mss'],
                      'columns': ['id',
                                  'symbol',
                                  'timeframe',
                                  'observed_at',
                                  'trend',
                                  'last_swing_high',
                                  'last_swing_low',
                                  'bos',
                                  'choch',
                                  'mss',
                                  'premium_discount',
                                  'evidence'],
                      'json': ['evidence'],
                      'uuid': []},
 'model_performance': {'bool': [],
                       'columns': ['id',
                                   'as_of',
                                   'setup_type',
                                   'symbol',
                                   'session',
                                   'regime',
                                   'sample_scope',
                                   'trades',
                                   'wins',
                                   'losses',
                                   'win_rate',
                                   'avg_win_r',
                                   'avg_loss_r',
                                   'expectancy_r',
                                   'profit_factor',
                                   'max_drawdown_r',
                                   'metadata'],
                       'json': ['metadata'],
                       'uuid': []},
 'pair_rankings': {'bool': [],
                   'columns': ['id',
                               'run_id',
                               'observed_at',
                               'symbol',
                               'direction',
                               'macro_edge',
                               'technical_edge',
                               'cross_asset_score',
                               'session_score',
                               'volatility_score',
                               'spread_score',
                               'pair_opportunity_score',
                               'rank',
                               'coverage',
                               'created_at'],
                   'json': [],
                   'uuid': []},
 'paper_trades': {'bool': [],
                  'columns': ['id',
                              'signal_id',
                              'entry_time',
                              'entry_price',
                              'exit_time',
                              'exit_price',
                              'spread_cost',
                              'commission',
                              'slippage',
                              'result_r',
                              'mae_r',
                              'mfe_r',
                              'status',
                              'created_at'],
                  'json': [],
                  'uuid': ['id']},
 'runtime_heartbeats': {'bool': ['healthy'],
                        'columns': ['worker_name',
                                    'observed_at',
                                    'healthy',
                                    'lag_seconds',
                                    'details'],
                        'json': ['details'],
                        'uuid': []},
 'scanner_runs': {'bool': [],
                  'columns': ['id',
                              'started_at',
                              'finished_at',
                              'mode',
                              'status',
                              'code_version',
                              'data_contract_version',
                              'created_at'],
                  'json': [],
                  'uuid': ['id']},
 'signals': {'bool': [],
             'columns': ['id',
                         'run_id',
                         'observed_at',
                         'symbol',
                         'direction',
                         'setup_type',
                         'state',
                         'pair_score',
                         'execution_score',
                         'final_score',
                         'entry_low',
                         'entry_high',
                         'sl',
                         'tp1',
                         'tp2',
                         'tp3',
                         'rr1',
                         'rr2',
                         'rr3',
                         'macro_bias',
                         'h4_bias',
                         'h1_bias',
                         'active_guards',
                         'data_coverage',
                         'expires_at',
                         'created_at'],
             'json': ['active_guards'],
             'uuid': ['id']},
 'smc_features': {'bool': ['liquidity_sweep'],
                  'columns': ['id',
                              'symbol',
                              'timeframe',
                              'observed_at',
                              'fvg_type',
                              'fvg_low',
                              'fvg_high',
                              'order_block_type',
                              'ob_low',
                              'ob_high',
                              'displacement_score',
                              'liquidity_sweep',
                              'sweep_type',
                              'evidence'],
                  'json': ['evidence'],
                  'uuid': []},
 'storage_guard_audit': {'bool': ['applied'],
                         'columns': ['id',
                                     'observed_at',
                                     'database_bytes_before',
                                     'database_bytes_after',
                                     'mode',
                                     'applied',
                                     'rows_deleted',
                                     'details'],
                         'json': ['rows_deleted', 'details'],
                         'uuid': []},
 'xau_dom_pressure_samples': {'bool': [],
                              'columns': ['observed_at',
                                          'state',
                                          'dom_pressure_score',
                                          'last_imbalance',
                                          'mean_imbalance',
                                          'top5_bid_units',
                                          'top5_ask_units',
                                          'bid_top5_change',
                                          'ask_top5_change',
                                          'bid_wall_ratio',
                                          'ask_wall_ratio',
                                          'bid_wall_price',
                                          'ask_wall_price',
                                          'bid_wall_persistence',
                                          'ask_wall_persistence',
                                          'sample_count',
                                          'source',
                                          'created_at'],
                              'json': [],
                              'uuid': []},
 'xau_outcome_ledger': {'bool': ['tp1_hit',
                                 'tp2_hit',
                                 'stop_hit',
                                 'missed_execution'],
                        'columns': ['id',
                                    'episode_key',
                                    'episode_type',
                                    'strategy_id',
                                    'signal_id',
                                    'zone_id',
                                    'map_at',
                                    'observed_at',
                                    'direction',
                                    'grade',
                                    'score',
                                    'status',
                                    'execution_authority',
                                    'entry_price',
                                    'stop_price',
                                    'tp1_price',
                                    'tp2_price',
                                    'first_touch_at',
                                    'map_first_touch_at',
                                    'confirmed_at',
                                    'execution_ready_at',
                                    'order_accepted_at',
                                    'protection_verified_at',
                                    'outcome_at',
                                    'outcome_class',
                                    'mfe_points',
                                    'mae_points',
                                    'mfe_r',
                                    'mae_r',
                                    'tp1_hit',
                                    'tp2_hit',
                                    'stop_hit',
                                    'missed_execution',
                                    'metadata',
                                    'created_at',
                                    'updated_at'],
                        'json': ['metadata'],
                        'uuid': ['id']},
 'xau_prepared_plan_lifecycle': {'bool': ['tp1_hit',
                                          'tp2_hit',
                                          'stop_hit',
                                          'post_cancel_terminal_hit'],
                                 'columns': ['id',
                                             'plan_key',
                                             'signal_id',
                                             'zone_id',
                                             'map_at',
                                             'created_at',
                                             'updated_at',
                                             'direction',
                                             'grade',
                                             'zone_low',
                                             'zone_high',
                                             'entry_price',
                                             'stop_price',
                                             'tp1_price',
                                             'tp2_price',
                                             'lifecycle_state',
                                             'cancel_reason',
                                             'cancelled_at',
                                             'first_touch_at',
                                             'confirmed_at',
                                             'execution_ready_at',
                                             'order_accepted_at',
                                             'protection_verified_at',
                                             'outcome_at',
                                             'outcome_class',
                                             'tp1_hit',
                                             'tp2_hit',
                                             'stop_hit',
                                             'mfe_r',
                                             'mae_r',
                                             'post_cancel_terminal_hit',
                                             'metadata'],
                                 'json': ['metadata'],
                                 'uuid': ['id']},
 'xau_pressure_depth_episodes': {'bool': ['reaction_hit_050', 'invalidated'],
                                 'columns': ['episode_key',
                                             'signal_key',
                                             'zone_id',
                                             'direction',
                                             'timeframe',
                                             'first_touch_at',
                                             'outcome_at',
                                             'status',
                                             'first_touch_dom_state',
                                             'first_touch_dom_score',
                                             'first_touch_imbalance',
                                             'dom_pressure_slope',
                                             'opposing_dom_score',
                                             'pressure_bucket',
                                             'turning_depth',
                                             'max_depth_reached',
                                             'reaction_hit_050',
                                             'invalidated',
                                             'zone_low',
                                             'zone_high',
                                             'atr_points',
                                             'metadata',
                                             'created_at',
                                             'updated_at'],
                                 'json': ['metadata'],
                                 'uuid': []}}
