from __future__ import annotations

"""Research-only V382 calibration for C4 current-leg time-to-touch.

The frozen V376 C4 selector remains unchanged. This replay asks a different
question: once C4 has selected a main reversal zone at a causal snapshot, how
long does price take to first touch that selected zone?

Snapshots are sampled from completed H1 closes. Every forecast is generated by
the canonical production/demo V342+C4 engine using only bars known at the
snapshot timestamp. Future M1 bars are then used only for outcome measurement.
No execution authority is produced by this module.
"""

import argparse
import json
from bisect import bisect_left, bisect_right
from collections import Counter, defaultdict
from datetime import UTC, datetime, timedelta
from math import isfinite
from pathlib import Path
from typing import Any, Iterable, Sequence

import numpy as np
import pandas as pd

from fx_scanner.models import Bar, ensure_utc
from fx_scanner.research_xau_sd_liquidity_v345 import (
    bars_from_frame,
    load_price_frame,
    resample_ohlc,
)
from fx_scanner.xau_sd_liquidity_engine_v342 import TF_PARAMS, evaluate_sd_liquidity

SCHEMA = "XAU_V382_C4_TIME_TO_TOUCH_CALIBRATION_V1"
RULES = {"H4": "4h", "H1": "1h", "M15": "15min", "M5": "5min"}
TF_MINUTES = {"H4": 240, "H1": 60, "M15": 15, "M5": 5}
WINDOWS = {"H4": 400, "H1": 560, "M15": 256, "M5": 384}
PROBABILITY_HORIZONS_HOURS = (6.0, 12.0, 24.0, 48.0, 72.0, 120.0, 240.0, 480.0)
MAX_FORWARD_HOURS = 24.0 * 30.0
MIN_CELL_N = 30


def _safe_float(value: Any) -> float | None:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    return parsed if isfinite(parsed) else None


def _iso(value: Any) -> datetime | None:
    if value in (None, ""):
        return None
    if isinstance(value, datetime):
        return ensure_utc(value)
    try:
        return ensure_utc(datetime.fromisoformat(str(value).replace("Z", "+00:00")))
    except (TypeError, ValueError):
        return None


def _rank_bucket(value: Any) -> str:
    try:
        rank = int(value)
    except (TypeError, ValueError):
        return "UNKNOWN"
    if rank <= 1:
        return "R1"
    if rank == 2:
        return "R2"
    return "R3_PLUS"


def _horizon_bucket(distance_atr: Any) -> str:
    value = _safe_float(distance_atr)
    if value is None:
        return "UNKNOWN"
    if value <= 1.0:
        return "NEAR"
    if value <= 3.0:
        return "MEDIUM"
    if value <= 6.0:
        return "FAR"
    return "VERY_FAR"


def _bar_cache(price: pd.DataFrame) -> tuple[dict[str, tuple[Bar, ...]], dict[str, list[datetime]]]:
    bars: dict[str, tuple[Bar, ...]] = {}
    completed_at: dict[str, list[datetime]] = {}
    for tf, rule in RULES.items():
        frame = resample_ohlc(price, rule)
        rows = bars_from_frame(frame, tf)
        bars[tf] = rows
        delta = timedelta(minutes=TF_MINUTES[tf])
        completed_at[tf] = [ensure_utc(row.timestamp) + delta for row in rows]
    return bars, completed_at


def _completed_bars(
    bars: dict[str, tuple[Bar, ...]],
    completed_at: dict[str, list[datetime]],
    timeframe: str,
    as_of: datetime,
) -> tuple[Bar, ...]:
    ends = completed_at[timeframe]
    idx = bisect_right(ends, ensure_utc(as_of))
    start = max(0, idx - WINDOWS[timeframe])
    return bars[timeframe][start:idx]


def _candidate_snapshots(
    h1_completed_at: Sequence[datetime],
    *,
    year: int,
    stride_hours: int,
) -> list[datetime]:
    candidates = [ts for ts in h1_completed_at if ensure_utc(ts).year == year]
    if stride_hours <= 1:
        return candidates
    output: list[datetime] = []
    last: datetime | None = None
    for raw in candidates:
        ts = ensure_utc(raw)
        if last is None or (ts - last).total_seconds() >= stride_hours * 3600.0 - 1.0:
            output.append(ts)
            last = ts
    return output


def _m1_arrays(price: pd.DataFrame) -> dict[str, Any]:
    return {
        "timestamps": [ensure_utc(pd.Timestamp(x).to_pydatetime()) for x in price["timestamp"]],
        "high": price["high"].to_numpy(dtype=float, copy=False),
        "low": price["low"].to_numpy(dtype=float, copy=False),
        "close": price["close"].to_numpy(dtype=float, copy=False),
    }


def _price_before(arrays: dict[str, Any], as_of: datetime) -> float | None:
    timestamps: list[datetime] = arrays["timestamps"]
    idx = bisect_left(timestamps, ensure_utc(as_of)) - 1
    if idx < 0:
        return None
    return float(arrays["close"][idx])


def _zone_expiry(zone: dict[str, Any], as_of: datetime) -> datetime | None:
    tf = str(zone.get("timeframe") or "")
    available = _iso(zone.get("available_at"))
    params = dict(TF_PARAMS.get(tf) or {})
    lifecycle = _safe_float(params.get("lifecycle_hours"))
    if available is None or lifecycle is None or lifecycle <= 0:
        return None
    expiry = available + timedelta(hours=lifecycle)
    return expiry if expiry > ensure_utc(as_of) else ensure_utc(as_of)


def _first_touch(
    arrays: dict[str, Any],
    *,
    as_of: datetime,
    zone: dict[str, Any],
    max_forward_hours: float,
) -> dict[str, Any]:
    timestamps: list[datetime] = arrays["timestamps"]
    low = float(zone["low"])
    high = float(zone["high"])
    start = bisect_left(timestamps, ensure_utc(as_of))
    if start >= len(timestamps):
        return {
            "touched": False,
            "observed_hours": 0.0,
            "calendar_hours": None,
            "market_hours": None,
            "touch_at": None,
            "censor_reason": "NO_FORWARD_DATA",
        }

    requested_end = ensure_utc(as_of) + timedelta(hours=max_forward_hours)
    expiry = _zone_expiry(zone, as_of)
    end_at = requested_end if expiry is None else min(requested_end, expiry)
    data_end = timestamps[-1] + timedelta(minutes=1)
    censor_reason = "MAX_FORWARD_HORIZON"
    if expiry is not None and expiry <= requested_end:
        censor_reason = "ZONE_LIFECYCLE_END"
    if data_end < end_at:
        end_at = data_end
        censor_reason = "DATA_END"

    end = bisect_left(timestamps, end_at)
    end = min(max(end, start), len(timestamps))
    if end <= start:
        observed = max(0.0, (end_at - ensure_utc(as_of)).total_seconds() / 3600.0)
        return {
            "touched": False,
            "observed_hours": observed,
            "calendar_hours": None,
            "market_hours": 0.0,
            "touch_at": None,
            "censor_reason": censor_reason,
        }

    lows = arrays["low"][start:end]
    highs = arrays["high"][start:end]
    matches = np.flatnonzero((lows <= high) & (highs >= low))
    if len(matches):
        absolute = start + int(matches[0])
        touch_at = timestamps[absolute] + timedelta(minutes=1)
        calendar_hours = max(0.0, (touch_at - ensure_utc(as_of)).total_seconds() / 3600.0)
        market_hours = (absolute - start + 1) / 60.0
        return {
            "touched": True,
            "observed_hours": calendar_hours,
            "calendar_hours": calendar_hours,
            "market_hours": market_hours,
            "touch_at": touch_at.isoformat(),
            "censor_reason": None,
        }

    observed = max(0.0, (end_at - ensure_utc(as_of)).total_seconds() / 3600.0)
    market_hours = (end - start) / 60.0
    return {
        "touched": False,
        "observed_hours": observed,
        "calendar_hours": None,
        "market_hours": market_hours,
        "touch_at": None,
        "censor_reason": censor_reason,
    }


def _kaplan_meier(rows: Sequence[dict[str, Any]]) -> dict[str, Any]:
    observations: list[tuple[float, bool]] = []
    for row in rows:
        event = bool(row.get("touched"))
        value = row.get("calendar_hours") if event else row.get("observed_hours")
        hours = _safe_float(value)
        if hours is None or hours < 0:
            continue
        observations.append((hours, event))
    observations.sort(key=lambda item: item[0])
    if not observations:
        return {
            "n": 0,
            "events": 0,
            "censored": 0,
            "event_rate_raw": None,
            "km_touch_probability": {},
            "km_q25_hours": None,
            "km_median_hours": None,
            "km_q75_hours": None,
            "km_q90_hours": None,
        }

    grouped: dict[float, list[bool]] = defaultdict(list)
    for hours, event in observations:
        grouped[hours].append(event)

    at_risk = len(observations)
    survival = 1.0
    curve: list[tuple[float, float]] = []
    for hours in sorted(grouped):
        flags = grouped[hours]
        events = sum(flags)
        censored = len(flags) - events
        if at_risk > 0 and events:
            survival *= max(0.0, 1.0 - events / at_risk)
        curve.append((hours, 1.0 - survival))
        at_risk -= events + censored

    def cdf_at(hours: float) -> float:
        value = 0.0
        for t, cdf in curve:
            if t > hours:
                break
            value = cdf
        return value

    def quantile(probability: float) -> float | None:
        for hours, cdf in curve:
            if cdf + 1e-12 >= probability:
                return float(hours)
        return None

    event_count = sum(1 for _, event in observations if event)
    event_hours = [hours for hours, event in observations if event]
    return {
        "n": len(observations),
        "events": event_count,
        "censored": len(observations) - event_count,
        "event_rate_raw": event_count / len(observations),
        "km_touch_probability": {
            str(int(h) if float(h).is_integer() else h): cdf_at(float(h))
            for h in PROBABILITY_HORIZONS_HOURS
        },
        "km_q25_hours": quantile(0.25),
        "km_median_hours": quantile(0.50),
        "km_q75_hours": quantile(0.75),
        "km_q90_hours": quantile(0.90),
        "touched_calendar_hours_raw_p50": None if not event_hours else float(np.quantile(event_hours, 0.50)),
        "touched_calendar_hours_raw_p75": None if not event_hours else float(np.quantile(event_hours, 0.75)),
        "touched_calendar_hours_raw_p90": None if not event_hours else float(np.quantile(event_hours, 0.90)),
        "max_observed_hours": max(hours for hours, _ in observations),
    }


def _group_summary(rows: Sequence[dict[str, Any]]) -> dict[str, Any]:
    km = _kaplan_meier(rows)
    censor_counts = Counter(str(r.get("censor_reason") or "TOUCHED") for r in rows)
    market_hours = [
        float(r["market_hours"])
        for r in rows
        if bool(r.get("touched")) and _safe_float(r.get("market_hours")) is not None
    ]
    km["censor_reason_counts"] = dict(censor_counts)
    km["touched_market_hours_p50"] = None if not market_hours else float(np.quantile(market_hours, 0.50))
    km["touched_market_hours_p75"] = None if not market_hours else float(np.quantile(market_hours, 0.75))
    km["reliable_cell"] = bool(
        int(km.get("n") or 0) >= MIN_CELL_N
        and int(km.get("events") or 0) >= max(12, MIN_CELL_N // 3)
    )
    return km


def _summaries(rows: Sequence[dict[str, Any]]) -> dict[str, Any]:
    output: dict[str, Any] = {"ALL": _group_summary(rows)}

    def keyed(fields: Sequence[str]) -> dict[str, Any]:
        buckets: dict[str, list[dict[str, Any]]] = defaultdict(list)
        for row in rows:
            key = "|".join(str(row.get(field) or "UNKNOWN") for field in fields)
            buckets[key].append(row)
        return {key: _group_summary(bucket) for key, bucket in sorted(buckets.items())}

    output["BY_HORIZON"] = keyed(("horizon",))
    output["BY_TIMEFRAME"] = keyed(("target_timeframe",))
    output["BY_DIRECTION"] = keyed(("now_direction",))
    output["BY_PATH_RANK"] = keyed(("path_rank_bucket",))
    output["BY_TIMEFRAME_HORIZON"] = keyed(("target_timeframe", "horizon"))
    output["BY_TIMEFRAME_HORIZON_DIRECTION"] = keyed(
        ("target_timeframe", "horizon", "now_direction")
    )
    output["BY_TIMEFRAME_HORIZON_RANK"] = keyed(
        ("target_timeframe", "horizon", "path_rank_bucket")
    )
    output["BY_EXACT_CELL"] = keyed(
        ("target_timeframe", "horizon", "path_rank_bucket", "now_direction")
    )
    return output


def _compact_reliable_cells(summary: dict[str, Any]) -> list[dict[str, Any]]:
    cells: list[dict[str, Any]] = []
    for key, row in dict(summary.get("BY_EXACT_CELL") or {}).items():
        if not bool(row.get("reliable_cell")):
            continue
        parts = key.split("|")
        cells.append(
            {
                "timeframe": parts[0] if len(parts) > 0 else "UNKNOWN",
                "horizon": parts[1] if len(parts) > 1 else "UNKNOWN",
                "path_rank_bucket": parts[2] if len(parts) > 2 else "UNKNOWN",
                "now_direction": parts[3] if len(parts) > 3 else "UNKNOWN",
                "n": row.get("n"),
                "events": row.get("events"),
                "km_median_hours": row.get("km_median_hours"),
                "km_q25_hours": row.get("km_q25_hours"),
                "km_q75_hours": row.get("km_q75_hours"),
                "touch_probability_24h": dict(row.get("km_touch_probability") or {}).get("24"),
                "touch_probability_72h": dict(row.get("km_touch_probability") or {}).get("72"),
                "touch_probability_120h": dict(row.get("km_touch_probability") or {}).get("120"),
            }
        )
    return cells


def run(
    year: int,
    csv_path: Path,
    output: Path,
    *,
    stride_hours: int = 4,
    max_forward_hours: float = MAX_FORWARD_HOURS,
) -> dict[str, Any]:
    price = load_price_frame(csv_path)
    arrays = _m1_arrays(price)
    bars, completed_at = _bar_cache(price)
    snapshots = _candidate_snapshots(
        completed_at["H1"],
        year=year,
        stride_hours=max(1, int(stride_hours)),
    )

    rows: list[dict[str, Any]] = []
    state_counts: Counter[str] = Counter()
    attempted = 0
    insufficient = 0
    engine_errors = 0

    for index, as_of in enumerate(snapshots, start=1):
        attempted += 1
        windows = {
            tf: _completed_bars(bars, completed_at, tf, as_of)
            for tf in RULES
        }
        if (
            len(windows["H4"]) < 24
            or len(windows["H1"]) < 24
            or len(windows["M15"]) < 20
            or len(windows["M5"]) < 20
        ):
            insufficient += 1
            continue
        price_now = _price_before(arrays, as_of)
        if price_now is None:
            insufficient += 1
            continue

        try:
            evaluation = evaluate_sd_liquidity(
                bars_h1=windows["H1"],
                bars_h4=windows["H4"],
                bars_m15=windows["M15"],
                bars_m5=windows["M5"],
                as_of=as_of,
                price_now=price_now,
            )
        except Exception as exc:  # research must count failures instead of hiding them
            engine_errors += 1
            state_counts[f"ENGINE_ERROR:{type(exc).__name__}"] += 1
            continue

        leg = dict(evaluation.get("current_leg_forecast") or {})
        state = str(leg.get("state") or "UNAVAILABLE")
        state_counts[state] += 1
        if state != "TOWARD_NEXT_REVERSAL_ZONE":
            continue

        zone = dict(evaluation.get("main_reversal_zone") or evaluation.get("decision_zone") or {})
        if not zone:
            continue
        path = dict(zone.get("next_zone_path") or {})
        tf = str(zone.get("timeframe") or "UNKNOWN")
        future = _first_touch(
            arrays,
            as_of=as_of,
            zone=zone,
            max_forward_hours=float(max_forward_hours),
        )
        distance_atr = _safe_float(leg.get("distance_atr"))
        checkpoint = dict(leg.get("checkpoint") or {})
        rows.append(
            {
                "as_of": ensure_utc(as_of).isoformat(),
                "price_now": float(price_now),
                "engine_contract": evaluation.get("contract"),
                "champion_id": dict(evaluation.get("champion") or {}).get("id"),
                "now_direction": str(leg.get("direction") or "WAIT"),
                "next_reversal_direction": str(leg.get("next_reversal_direction") or "WAIT"),
                "target_zone_id": zone.get("zone_id"),
                "target_timeframe": tf,
                "target_low": float(zone["low"]),
                "target_high": float(zone["high"]),
                "target_atr": _safe_float(zone.get("atr")),
                "path_rank": path.get("path_rank"),
                "path_rank_bucket": _rank_bucket(path.get("path_rank")),
                "path_blockers": path.get("blockers"),
                "distance_points": _safe_float(leg.get("distance_points")),
                "distance_atr": distance_atr,
                "horizon": str(leg.get("horizon") or _horizon_bucket(distance_atr)),
                "checkpoint_price": _safe_float(checkpoint.get("price")),
                "checkpoint_timeframe": checkpoint.get("timeframe"),
                "checkpoint_zone_id": checkpoint.get("zone_id"),
                **future,
            }
        )
        if index % 250 == 0:
            print(
                f"PROGRESS year={year} snapshots={index}/{len(snapshots)} "
                f"calibration_rows={len(rows)} touches={sum(bool(r.get('touched')) for r in rows)}"
            )

    summaries = _summaries(rows)
    payload = {
        "schema": SCHEMA,
        "year": year,
        "generated_at": datetime.now(tz=UTC).isoformat(),
        "source": "HISTDATA_XAUUSD_M1_PUBLIC_SECONDARY",
        "causal": True,
        "execution_authority": False,
        "execution_influence": False,
        "champion_under_test": "V376_C4_NEXT_ZONE_PATH",
        "engine_under_test": "CANONICAL_XAU_RIZAN_SD_LIQUIDITY_V342_WITH_V381_CURRENT_LEG",
        "purpose": "Calibrate causal time-to-first-touch for the main reversal zone selected by frozen C4, so NOW-path horizon can be expressed empirically without changing C4 selection or execution logic.",
        "snapshot_stride_hours": int(stride_hours),
        "max_forward_hours": float(max_forward_hours),
        "probability_horizons_hours": list(PROBABILITY_HORIZONS_HOURS),
        "minimum_reliable_cell_n": MIN_CELL_N,
        "attempted_snapshots": attempted,
        "insufficient_snapshots": insufficient,
        "engine_errors": engine_errors,
        "eligible_forecast_count": len(rows),
        "touch_count": sum(bool(r.get("touched")) for r in rows),
        "state_counts": dict(state_counts),
        "summary": summaries,
        "reliable_exact_cells": _compact_reliable_cells(summaries),
        "rows": rows,
        "limitations": [
            "Public M1 OHLC is used for first-touch timing; bid/ask spread and tick ordering are not reconstructed.",
            "Consecutive four-hour snapshots can refer to the same persistent zone; estimates describe an arbitrary causal observation time rather than independent zone births.",
            "Calendar-hour estimates include market-closed gaps such as weekends; market-hour quantiles are also reported for touched forecasts.",
            "A selected zone can be replaced by a newer C4 decision before the original zone is touched; V382 measures the original snapshot forecast and does not retrospectively rewrite it.",
            "No production clock ETA should be enabled until 2025 and 2026 stability and minimum-cell sample sizes are reviewed.",
        ],
    }
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        json.dumps(payload, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    print(
        "V382_C4_TIME_TO_TOUCH="
        + json.dumps(
            {
                "year": year,
                "attempted_snapshots": attempted,
                "eligible_forecasts": len(rows),
                "touches": payload["touch_count"],
                "all": summaries["ALL"],
                "reliable_exact_cells": len(payload["reliable_exact_cells"]),
            },
            sort_keys=True,
        )
    )
    print(f"OUTPUT={output}")
    return payload


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--year", type=int, required=True)
    parser.add_argument("--csv", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--stride-hours", type=int, default=4)
    parser.add_argument("--max-forward-hours", type=float, default=MAX_FORWARD_HOURS)
    args = parser.parse_args()
    run(
        args.year,
        args.csv,
        args.output,
        stride_hours=args.stride_hours,
        max_forward_hours=args.max_forward_hours,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
