from fx_scanner.research_xau_afic_h4_map_selector_v161 import (
    BODY_FRACTION_MAX,DIRECTIONAL_CLOSE_LOCATION_MAX,EXECUTION_INFLUENCE,
    PRIMARY_SELECTOR,PROMOTION_ELIGIBLE,ZONE_DISTANCE_ATR_MAX
)
def test_v161_frozen_primary():
    assert EXECUTION_INFLUENCE is False
    assert PROMOTION_ELIGIBLE is False
    assert PRIMARY_SELECTOR=="NEAR_WEAK_H4_CLOSE"
    assert ZONE_DISTANCE_ATR_MAX==0.75
    assert DIRECTIONAL_CLOSE_LOCATION_MAX==0.65
    assert BODY_FRACTION_MAX==0.55
