from fx_scanner.research_xau_v110_100usd_no_risk_v112 import ACCOUNT_LEVERAGE,STARTING_BALANCE_USD,DYNAMIC_MAX_LOT,POLICY_EFFECT,EXECUTION_INFLUENCE,PROMOTION_ELIGIBLE
def test_v112_contract():
    assert ACCOUNT_LEVERAGE==100.0
    assert STARTING_BALANCE_USD==100.0
    assert DYNAMIC_MAX_LOT==0.50
    assert POLICY_EFFECT=="SHADOW_ONLY"
    assert EXECUTION_INFLUENCE is False
    assert PROMOTION_ELIGIBLE is False
