from fx_scanner.research_xau_v142_retest_entry_v143 import ENTRY_MODES,EXECUTION_INFLUENCE,PROMOTION_ELIGIBLE,RETEST_BARS
def test_v143_frozen_entry_contract():
    assert EXECUTION_INFLUENCE is False
    assert PROMOTION_ELIGIBLE is False
    assert ENTRY_MODES==("BASELINE_NEXT_OPEN","BREAKOUT_LEVEL_RETEST_2BAR","DISPLACEMENT_BODY50_RETEST_2BAR","FVG50_RETEST_3BAR")
    assert RETEST_BARS["BREAKOUT_LEVEL_RETEST_2BAR"]==2
    assert RETEST_BARS["FVG50_RETEST_3BAR"]==3
