from fx_scanner.research_xau_pullback_bootstrap_v91 import VARIANTS,PENDING_WINDOW_BARS,STARTING_BALANCE,POLICY_EFFECT,EXECUTION_INFLUENCE,PROMOTION_ELIGIBLE
def test_v91_contract():
    assert VARIANTS==("BREAKOUT_LEVEL_RETEST_4","DISPLACEMENT_50_RETEST_4")
    assert PENDING_WINDOW_BARS==4
    assert STARTING_BALANCE==100.0
    assert POLICY_EFFECT=="SHADOW_ONLY"
    assert EXECUTION_INFLUENCE is False
    assert PROMOTION_ELIGIBLE is False
