-- FX Institutional Scanner v0.4
-- Declarative schema for a NEW dedicated FX Supabase project.
-- Do not apply this to existing stock-scanner projects.
-- No extension version pins are used.

create table if not exists public.fx_symbols (
  symbol text primary key,
  base_currency text not null check (char_length(base_currency) = 3),
  quote_currency text not null check (char_length(quote_currency) = 3),
  pip_size numeric not null check (pip_size > 0),
  tier text not null check (tier in ('A','B')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.scanner_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null,
  finished_at timestamptz,
  mode text not null check (mode in ('RESEARCH_ONLY','PAPER_ONLY','DEMO_ONLY','REAL_MONEY_CANDIDATE')),
  status text not null,
  code_version text not null,
  data_contract_version text not null default '0.4',
  created_at timestamptz not null default now()
);
create index if not exists scanner_runs_started_at_idx on public.scanner_runs (started_at desc);

create table if not exists public.data_quality_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid references public.scanner_runs(id) on delete cascade,
  symbol text not null references public.fx_symbols(symbol),
  observed_at timestamptz not null,
  record_count integer not null check (record_count >= 0),
  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  non_monotonic_count integer not null default 0 check (non_monotonic_count >= 0),
  stale boolean not null,
  spread_ratio double precision,
  valid boolean not null,
  issues jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists data_quality_symbol_time_idx on public.data_quality_snapshots (symbol, observed_at desc);

create table if not exists public.currency_macro_state (
  id bigint generated by default as identity primary key,
  currency text not null check (char_length(currency) = 3),
  observed_at timestamptz not null,
  rate_score double precision,
  central_bank_score double precision,
  inflation_score double precision,
  growth_score double precision,
  labour_score double precision,
  yield_score double precision,
  risk_score double precision,
  positioning_score double precision,
  macro_score double precision,
  coverage double precision not null check (coverage between 0 and 1),
  freshness_seconds integer not null check (freshness_seconds >= 0),
  evidence jsonb not null default '{}'::jsonb,
  unique (currency, observed_at)
);
create index if not exists currency_macro_state_idx on public.currency_macro_state (currency, observed_at desc);

create table if not exists public.currency_strength (
  id bigint generated by default as identity primary key,
  currency text not null check (char_length(currency) = 3),
  observed_at timestamptz not null,
  strength_15m double precision,
  strength_1h double precision,
  strength_4h double precision,
  strength_1d double precision,
  combined_strength double precision,
  coverage double precision not null check (coverage between 0 and 1),
  unique (currency, observed_at)
);

create table if not exists public.pair_rankings (
  id bigint generated by default as identity primary key,
  run_id uuid references public.scanner_runs(id) on delete cascade,
  observed_at timestamptz not null,
  symbol text not null references public.fx_symbols(symbol),
  direction text check (direction in ('LONG','SHORT','NEUTRAL')),
  macro_edge double precision,
  technical_edge double precision,
  cross_asset_score double precision,
  session_score double precision,
  volatility_score double precision,
  spread_score double precision,
  pair_opportunity_score double precision check (pair_opportunity_score between 0 and 100),
  rank integer check (rank > 0),
  coverage double precision not null check (coverage between 0 and 1),
  created_at timestamptz not null default now()
);
create index if not exists pair_rankings_run_rank_idx on public.pair_rankings (run_id, rank);

create table if not exists public.market_structure (
  id bigint generated by default as identity primary key,
  symbol text not null references public.fx_symbols(symbol),
  timeframe text not null check (timeframe in ('M1','M5','M15','H1','H4','D1')),
  observed_at timestamptz not null,
  trend text,
  last_swing_high double precision,
  last_swing_low double precision,
  bos boolean,
  choch boolean,
  mss boolean,
  premium_discount double precision,
  evidence jsonb not null default '{}'::jsonb,
  unique (symbol, timeframe, observed_at)
);

create table if not exists public.liquidity_levels (
  id bigint generated by default as identity primary key,
  symbol text not null references public.fx_symbols(symbol),
  timeframe text not null,
  observed_at timestamptz not null,
  level double precision not null,
  level_type text not null,
  strength double precision,
  touch_count integer not null default 1 check (touch_count > 0),
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists liquidity_active_idx on public.liquidity_levels (symbol, active, observed_at desc);

create table if not exists public.smc_features (
  id bigint generated by default as identity primary key,
  symbol text not null references public.fx_symbols(symbol),
  timeframe text not null,
  observed_at timestamptz not null,
  fvg_type text,
  fvg_low double precision,
  fvg_high double precision,
  order_block_type text,
  ob_low double precision,
  ob_high double precision,
  displacement_score double precision,
  liquidity_sweep boolean,
  sweep_type text,
  evidence jsonb not null default '{}'::jsonb
);

create table if not exists public.signals (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.scanner_runs(id) on delete set null,
  observed_at timestamptz not null,
  symbol text not null references public.fx_symbols(symbol),
  direction text not null check (direction in ('LONG','SHORT')),
  setup_type text not null,
  state text not null check (state in ('NO_TRADE','WATCH','SETUP_FORMING','ARMED','EXECUTION_READY','MISSED','INVALIDATED','COOLDOWN')),
  pair_score double precision check (pair_score between 0 and 100),
  execution_score double precision check (execution_score between 0 and 100),
  final_score double precision check (final_score between 0 and 100),
  entry_low double precision,
  entry_high double precision,
  sl double precision,
  tp1 double precision,
  tp2 double precision,
  tp3 double precision,
  rr1 double precision,
  rr2 double precision,
  rr3 double precision,
  macro_bias text,
  h4_bias text,
  h1_bias text,
  active_guards jsonb not null default '[]'::jsonb,
  data_coverage double precision not null check (data_coverage between 0 and 1),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists signals_symbol_time_idx on public.signals (symbol, observed_at desc);
create index if not exists signals_state_time_idx on public.signals (state, observed_at desc);

create table if not exists public.paper_trades (
  id uuid primary key default gen_random_uuid(),
  signal_id uuid not null references public.signals(id) on delete restrict,
  entry_time timestamptz not null,
  entry_price double precision not null,
  exit_time timestamptz,
  exit_price double precision,
  spread_cost double precision,
  commission double precision,
  slippage double precision,
  result_r double precision,
  mae_r double precision,
  mfe_r double precision,
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.model_performance (
  id bigint generated by default as identity primary key,
  as_of timestamptz not null,
  setup_type text not null,
  symbol text,
  session text,
  regime text,
  sample_scope text not null,
  trades integer not null check (trades >= 0),
  wins integer not null check (wins >= 0),
  losses integer not null check (losses >= 0),
  win_rate double precision,
  avg_win_r double precision,
  avg_loss_r double precision,
  expectancy_r double precision,
  profit_factor double precision,
  max_drawdown_r double precision,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.fx_symbols enable row level security;
alter table public.scanner_runs enable row level security;
alter table public.data_quality_snapshots enable row level security;
alter table public.currency_macro_state enable row level security;
alter table public.currency_strength enable row level security;
alter table public.pair_rankings enable row level security;
alter table public.market_structure enable row level security;
alter table public.liquidity_levels enable row level security;
alter table public.smc_features enable row level security;
alter table public.signals enable row level security;
alter table public.paper_trades enable row level security;
alter table public.model_performance enable row level security;

revoke all on table public.fx_symbols from anon, authenticated;
revoke all on table public.scanner_runs from anon, authenticated;
revoke all on table public.data_quality_snapshots from anon, authenticated;
revoke all on table public.currency_macro_state from anon, authenticated;
revoke all on table public.currency_strength from anon, authenticated;
revoke all on table public.pair_rankings from anon, authenticated;
revoke all on table public.market_structure from anon, authenticated;
revoke all on table public.liquidity_levels from anon, authenticated;
revoke all on table public.smc_features from anon, authenticated;
revoke all on table public.signals from anon, authenticated;
revoke all on table public.paper_trades from anon, authenticated;
revoke all on table public.model_performance from anon, authenticated;

-- v0.4 mobile/control-plane and broker telemetry.
-- These tables are operational state only; realtime quote/order execution must
-- not synchronously depend on Supabase latency.
create table if not exists public.broker_accounts (
  backend text not null check (backend in ('CTRADER','MT5')),
  account_id text not null,
  broker_name text,
  environment text not null check (environment in ('DEMO','LIVE')),
  enabled boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (backend, account_id)
);

create table if not exists public.execution_control (
  control_key text primary key default 'primary',
  execution_mode text not null default 'DISABLED'
    check (execution_mode in ('DISABLED','SIMULATION','CONFIRM_TO_TRADE','AUTO')),
  new_orders_enabled boolean not null default false,
  emergency_stop boolean not null default true,
  close_all_requested boolean not null default false,
  version bigint not null default 1,
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.runtime_heartbeats (
  worker_name text primary key,
  observed_at timestamptz not null,
  healthy boolean not null,
  lag_seconds double precision,
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.broker_order_events (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  backend text not null check (backend in ('CTRADER','MT5')),
  account_id text not null,
  signal_key text not null,
  broker_order_id text,
  event_type text not null,
  accepted boolean,
  code text,
  message text,
  payload jsonb not null default '{}'::jsonb
);
create index if not exists broker_order_events_signal_idx
  on public.broker_order_events (signal_key, observed_at desc);

alter table public.broker_accounts enable row level security;
alter table public.execution_control enable row level security;
alter table public.runtime_heartbeats enable row level security;
alter table public.broker_order_events enable row level security;

revoke all on table public.broker_accounts from anon, authenticated;
revoke all on table public.execution_control from anon, authenticated;
revoke all on table public.runtime_heartbeats from anon, authenticated;
revoke all on table public.broker_order_events from anon, authenticated;


-- New Supabase projects no longer auto-grant Data API access.
-- Backend-only access: secret/service_role may use the Data API; public roles stay closed.
grant usage on schema public to service_role;
grant select, insert, update, delete on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;
alter default privileges in schema public grant select, insert, update, delete on tables to service_role;
alter default privileges in schema public grant usage, select on sequences to service_role;

-- Fail-closed initial mobile/control-plane state.
insert into public.execution_control
  (control_key, execution_mode, new_orders_enabled, emergency_stop, close_all_requested, version, metadata)
values
  ('primary', 'DISABLED', false, true, false, 1, '{"source":"bootstrap_v0.4"}'::jsonb)
on conflict (control_key) do nothing;


-- v0.4 advisor hardening: cover foreign keys used by deletes/joins.
create index if not exists data_quality_run_id_idx
  on public.data_quality_snapshots (run_id);
create index if not exists pair_rankings_symbol_idx
  on public.pair_rankings (symbol);
create index if not exists paper_trades_signal_id_idx
  on public.paper_trades (signal_id);
create index if not exists signals_run_id_idx
  on public.signals (run_id);
create index if not exists smc_features_symbol_idx
  on public.smc_features (symbol);

-- Explicit deny policies for low-privilege API roles. Backend secret/service_role
-- bypasses RLS; anon/authenticated stay denied even if grants change later.
do $$
declare
  t text;
begin
  foreach t in array ARRAY[
    'fx_symbols','scanner_runs','data_quality_snapshots','currency_macro_state',
    'currency_strength','pair_rankings','market_structure','liquidity_levels',
    'smc_features','signals','paper_trades','model_performance',
    'broker_accounts','execution_control','runtime_heartbeats','broker_order_events'
  ]
  loop
    begin
      execute format(
        'create policy %I on public.%I as restrictive for all to anon, authenticated using (false) with check (false)',
        'deny_public_' || t, t
      );
    exception when duplicate_object then
      null;
    end;
  end loop;
end $$;


-- v0.10 read-only broker account and open-position monitoring.
create table if not exists public.broker_account_state (
  backend text not null check (backend in ('CTRADER','MT5')),
  account_id text not null,
  snapshot_id uuid not null,
  observed_at timestamptz not null,
  broker_name text,
  environment text check (environment is null or environment in ('DEMO','LIVE')),
  currency text,
  balance double precision not null,
  equity double precision not null,
  floating_profit double precision,
  margin double precision,
  margin_free double precision,
  margin_level double precision,
  leverage double precision,
  trade_allowed boolean not null default false,
  connection_healthy boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  primary key (backend, account_id)
);

create table if not exists public.broker_position_state (
  backend text not null check (backend in ('CTRADER','MT5')),
  account_id text not null,
  position_id text not null,
  snapshot_id uuid not null,
  observed_at timestamptz not null,
  symbol text not null,
  side text not null check (side in ('BUY','SELL')),
  volume double precision not null check (volume >= 0),
  open_price double precision not null,
  current_price double precision,
  sl double precision,
  tp double precision,
  profit double precision,
  swap double precision,
  magic bigint,
  comment text,
  opened_at timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  primary key (backend, account_id, position_id)
);
create index if not exists broker_position_state_snapshot_idx
  on public.broker_position_state (backend, account_id, snapshot_id);
alter table public.broker_account_state enable row level security;
alter table public.broker_position_state enable row level security;
revoke all on table public.broker_account_state from anon, authenticated;
revoke all on table public.broker_position_state from anon, authenticated;
grant select, insert, update, delete on table public.broker_account_state to service_role;
grant select, insert, update, delete on table public.broker_position_state to service_role;
do $$
begin
  begin
    create policy deny_public_broker_account_state
      on public.broker_account_state as restrictive for all to anon, authenticated
      using (false) with check (false);
  exception when duplicate_object then null;
  end;
  begin
    create policy deny_public_broker_position_state
      on public.broker_position_state as restrictive for all to anon, authenticated
      using (false) with check (false);
  exception when duplicate_object then null;
  end;
end $$;


-- Prospective XAU outcome ledger + bounded storage guard.
-- The ledger is compact one-row-per-episode state. Raw broker/order evidence remains
-- in broker_order_events; this table is not automatically pruned.
create table if not exists public.xau_outcome_ledger (
  id uuid primary key default gen_random_uuid(),
  episode_key text not null unique,
  episode_type text not null,
  strategy_id text not null,
  signal_id uuid,
  zone_id text,
  map_at timestamptz,
  observed_at timestamptz not null,
  direction text check (direction is null or direction in ('LONG','SHORT')),
  grade text check (grade is null or grade in ('A','B','C')),
  score double precision,
  status text not null,
  execution_authority text,
  entry_price double precision,
  stop_price double precision,
  tp1_price double precision,
  tp2_price double precision,
  first_touch_at timestamptz,
  map_first_touch_at timestamptz,
  confirmed_at timestamptz,
  execution_ready_at timestamptz,
  order_accepted_at timestamptz,
  protection_verified_at timestamptz,
  outcome_at timestamptz,
  outcome_class text,
  mfe_points double precision,
  mae_points double precision,
  mfe_r double precision,
  mae_r double precision,
  tp1_hit boolean not null default false,
  tp2_hit boolean not null default false,
  stop_hit boolean not null default false,
  missed_execution boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists xau_outcome_ledger_observed_at_idx
  on public.xau_outcome_ledger (observed_at desc);
create index if not exists xau_outcome_ledger_status_idx
  on public.xau_outcome_ledger (status, observed_at desc);
create index if not exists xau_outcome_ledger_zone_map_idx
  on public.xau_outcome_ledger (zone_id, map_at);
create index if not exists xau_outcome_ledger_signal_id_idx
  on public.xau_outcome_ledger (signal_id)
  where signal_id is not null;

-- Compact one-row-per-prepared-plan AFIC lifecycle evidence. Raw state/event
-- history remains in broker_order_events; this table preserves why a plan
-- disappeared from the current dashboard without duplicating quote telemetry.
create table if not exists public.xau_prepared_plan_lifecycle (
  id uuid primary key default gen_random_uuid(),
  plan_key text not null unique,
  signal_id uuid not null,
  zone_id text,
  map_at timestamptz,
  created_at timestamptz not null,
  updated_at timestamptz not null default now(),
  direction text check (direction is null or direction in ('LONG','SHORT')),
  grade text check (grade is null or grade in ('A','B','C')),
  zone_low double precision,
  zone_high double precision,
  entry_price double precision,
  stop_price double precision,
  tp1_price double precision,
  tp2_price double precision,
  lifecycle_state text not null,
  cancel_reason text,
  cancelled_at timestamptz,
  first_touch_at timestamptz,
  confirmed_at timestamptz,
  execution_ready_at timestamptz,
  order_accepted_at timestamptz,
  protection_verified_at timestamptz,
  outcome_at timestamptz,
  outcome_class text,
  tp1_hit boolean not null default false,
  tp2_hit boolean not null default false,
  stop_hit boolean not null default false,
  mfe_r double precision,
  mae_r double precision,
  post_cancel_terminal_hit boolean not null default false,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists xau_prepared_plan_lifecycle_created_at_idx
  on public.xau_prepared_plan_lifecycle (created_at desc);
create index if not exists xau_prepared_plan_lifecycle_state_idx
  on public.xau_prepared_plan_lifecycle (lifecycle_state, created_at desc);
create index if not exists xau_prepared_plan_lifecycle_signal_id_idx
  on public.xau_prepared_plan_lifecycle (signal_id);
create index if not exists xau_prepared_plan_lifecycle_zone_map_idx
  on public.xau_prepared_plan_lifecycle (zone_id, map_at);

create table if not exists public.storage_guard_audit (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  database_bytes_before bigint not null,
  database_bytes_after bigint not null,
  mode text not null,
  applied boolean not null,
  rows_deleted jsonb not null default '{}'::jsonb,
  details jsonb not null default '{}'::jsonb
);
create index if not exists storage_guard_audit_observed_at_idx
  on public.storage_guard_audit (observed_at desc);

alter table public.xau_outcome_ledger enable row level security;
alter table public.xau_prepared_plan_lifecycle enable row level security;
alter table public.storage_guard_audit enable row level security;
revoke all on table public.xau_outcome_ledger from anon, authenticated;
revoke all on table public.xau_prepared_plan_lifecycle from anon, authenticated;
revoke all on table public.storage_guard_audit from anon, authenticated;
grant select, insert, update, delete on table public.xau_outcome_ledger to service_role;
grant select, insert, update, delete on table public.xau_prepared_plan_lifecycle to service_role;
grant select, insert, update, delete on table public.storage_guard_audit to service_role;
grant usage, select on sequence public.storage_guard_audit_id_seq to service_role;

do $$
begin
  begin
    create policy deny_public_xau_outcome_ledger
      on public.xau_outcome_ledger as restrictive for all to anon, authenticated
      using (false) with check (false);
  exception when duplicate_object then null;
  end;
  begin
    create policy deny_public_xau_prepared_plan_lifecycle
      on public.xau_prepared_plan_lifecycle as restrictive for all to anon, authenticated
      using (false) with check (false);
  exception when duplicate_object then null;
  end;
  begin
    create policy deny_public_storage_guard_audit
      on public.storage_guard_audit as restrictive for all to anon, authenticated
      using (false) with check (false);
  exception when duplicate_object then null;
  end;
end $$;

-- Storage policy: absolute ceiling 500 MiB. Retention acts well before the
-- ceiling because DELETE frees reusable pages but may not reduce allocated DB
-- size immediately. Critical broker execution events, xau_outcome_ledger, and
-- xau_prepared_plan_lifecycle are never pruned by this function.
create or replace function public.fx_storage_guard_v1(p_apply boolean default false)
returns jsonb
language plpgsql
set search_path = public, pg_catalog
as $$
declare
  mib constant bigint := 1024 * 1024;
  before_bytes bigint := pg_database_size(current_database());
  after_bytes bigint;
  mode text;
  pair_deleted bigint := 0;
  strength_deleted bigint := 0;
  latency_deleted bigint := 0;
  feature_deleted bigint := 0;
  signal_deleted bigint := 0;
  run_deleted bigint := 0;
  audit_deleted bigint := 0;
  pair_keep interval := interval '30 days';
  strength_keep interval := interval '30 days';
  latency_keep interval := interval '30 days';
  feature_keep interval := interval '90 days';
  signal_keep interval := interval '365 days';
begin
  if before_bytes < 350 * mib then
    mode := 'NORMAL';
  elsif before_bytes < 400 * mib then
    mode := 'WATCH';
  elsif before_bytes < 425 * mib then
    mode := 'PRESSURE';
    pair_keep := interval '21 days';
    strength_keep := interval '21 days';
    latency_keep := interval '21 days';
    feature_keep := interval '60 days';
  elsif before_bytes < 475 * mib then
    mode := 'HIGH';
    pair_keep := interval '14 days';
    strength_keep := interval '14 days';
    latency_keep := interval '14 days';
    feature_keep := interval '45 days';
    signal_keep := interval '180 days';
  else
    mode := 'CRITICAL';
    pair_keep := interval '7 days';
    strength_keep := interval '7 days';
    latency_keep := interval '7 days';
    feature_keep := interval '30 days';
    signal_keep := interval '90 days';
  end if;

  if p_apply then
    delete from public.pair_rankings
      where observed_at < now() - pair_keep;
    get diagnostics pair_deleted = row_count;

    delete from public.currency_strength
      where observed_at < now() - strength_keep;
    get diagnostics strength_deleted = row_count;

    delete from public.broker_order_events
      where event_type in ('DEMO_XAU_STRATEGY_LATENCY_V1','DEMO_XAU_STRATEGY_LATENCY_V2')
        and observed_at < now() - latency_keep;
    get diagnostics latency_deleted = row_count;

    delete from public.broker_order_events
      where event_type = 'DEMO_SIGNAL_FEATURE_SNAPSHOT_V2'
        and observed_at < now() - feature_keep;
    get diagnostics feature_deleted = row_count;

    if before_bytes >= 425 * mib then
      delete from public.signals s
        where s.observed_at < now() - signal_keep
          and s.setup_type not like 'AFIC_%'
          and s.state <> 'EXECUTION_READY'
          and not exists (
            select 1 from public.paper_trades p where p.signal_id = s.id
          )
          and not exists (
            select 1 from public.broker_order_events e
            where e.signal_key = s.id::text
          );
      get diagnostics signal_deleted = row_count;
    end if;

    delete from public.scanner_runs r
      where r.started_at < now() - greatest(pair_keep, interval '30 days')
        and not exists (
          select 1 from public.pair_rankings pr where pr.run_id = r.id
        )
        and not exists (
          select 1 from public.signals s where s.run_id = r.id
        )
        and not exists (
          select 1 from public.data_quality_snapshots d where d.run_id = r.id
        );
    get diagnostics run_deleted = row_count;

    delete from public.storage_guard_audit
      where observed_at < now() - interval '365 days';
    get diagnostics audit_deleted = row_count;
  end if;

  after_bytes := pg_database_size(current_database());

  insert into public.storage_guard_audit(
    database_bytes_before,database_bytes_after,mode,applied,rows_deleted,details
  )
  values (
    before_bytes,after_bytes,mode,p_apply,
    jsonb_build_object(
      'pair_rankings',pair_deleted,
      'currency_strength',strength_deleted,
      'latency_events',latency_deleted,
      'feature_snapshots',feature_deleted,
      'signals',signal_deleted,
      'scanner_runs',run_deleted,
      'guard_audit',audit_deleted
    ),
    jsonb_build_object(
      'contract','FOREX_SCANNER_STORAGE_GUARD_V1',
      'absolute_ceiling_mib',500,
      'watch_mib',350,
      'pressure_mib',400,
      'high_mib',425,
      'critical_mib',475,
      'critical_execution_events_pruned',false,
      'outcome_ledger_pruned',false,
      'allocated_database_size_may_not_shrink_after_delete',true
    )
  );

  return jsonb_build_object(
    'mode',mode,
    'applied',p_apply,
    'database_bytes_before',before_bytes,
    'database_bytes_after',after_bytes,
    'database_mib_before',round(before_bytes::numeric / mib,2),
    'database_mib_after',round(after_bytes::numeric / mib,2),
    'absolute_ceiling_mib',500,
    'rows_deleted',jsonb_build_object(
      'pair_rankings',pair_deleted,
      'currency_strength',strength_deleted,
      'latency_events',latency_deleted,
      'feature_snapshots',feature_deleted,
      'signals',signal_deleted,
      'scanner_runs',run_deleted,
      'guard_audit',audit_deleted
    )
  );
end;
$$;

revoke all on function public.fx_storage_guard_v1(boolean) from public, anon, authenticated;
grant execute on function public.fx_storage_guard_v1(boolean) to service_role;

-- V204 dashboard/read-path indexes. These do not alter trading logic.
-- The dashboard repeatedly reads the newest broker events, both globally and
-- by event_type+code. Keep both access paths explicit to avoid full-table
-- scan+sort growth as prospective evidence accumulates.
create index if not exists broker_order_events_observed_at_desc_idx
  on public.broker_order_events (observed_at desc);
create index if not exists broker_order_events_event_code_observed_idx
  on public.broker_order_events (event_type, code, observed_at desc);

-- Contract marker: XAU_PROSPECTIVE_OUTCOME_LEDGER_V1


-- V206 signal query budget: latest-signals dashboard path orders globally by
-- observed_at and cannot use the state- or symbol-prefixed indexes. This small
-- index removes a full signals scan+sort on each cached dashboard refresh.
-- Retention remains conservative: V206 does not delete historical signals.
create index if not exists signals_observed_at_desc_idx
  on public.signals (observed_at desc);

-- V206 HOT/WARM/COLD retention contract (policy marker only):
-- HOT: recent/active operational signals; WARM: research history retained in
-- signals; COLD deletion remains delegated to fx_storage_guard_v1 only under
-- HIGH/CRITICAL storage pressure with execution/evidence exclusions intact.
-- Contract marker: FOREX_SCANNER_SIGNAL_QUERY_BUDGET_V206


-- V207 broker-event hot path. Production pg_stat_statements showed the
-- backend+event_type+account_id newest-first read path executing >16k times.
-- This index lets PostgreSQL filter and order in one access path.
create index if not exists broker_order_events_backend_event_account_observed_idx
  on public.broker_order_events (backend, event_type, account_id, observed_at desc);

-- Contract marker: FOREX_SCANNER_BROKER_EVENT_HOT_PATH_V207
