-- FX Institutional Scanner v0.1
-- Declarative schema for a NEW dedicated FX Supabase project.
-- Do not apply this to existing stock-scanner projects.
-- No extension version pins are used.

create table if not exists public.fx_symbols (
  symbol text primary key,
  base_currency text not null check (char_length(base_currency) = 3),
  quote_currency text not null check (char_length(quote_currency) = 3),
  pip_size numeric not null check (pip_size > 0),
  tier text not null check (tier in ('A','B')),
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.scanner_runs (
  id uuid primary key default gen_random_uuid(),
  started_at timestamptz not null,
  finished_at timestamptz,
  mode text not null check (mode in ('RESEARCH_ONLY','PAPER_ONLY','DEMO_ONLY','REAL_MONEY_CANDIDATE')),
  status text not null,
  code_version text not null,
  data_contract_version text not null default '0.1',
  created_at timestamptz not null default now()
);
create index if not exists scanner_runs_started_at_idx on public.scanner_runs (started_at desc);

create table if not exists public.data_quality_snapshots (
  id bigint generated by default as identity primary key,
  run_id uuid references public.scanner_runs(id) on delete cascade,
  symbol text not null references public.fx_symbols(symbol),
  observed_at timestamptz not null,
  record_count integer not null check (record_count >= 0),
  duplicate_count integer not null default 0 check (duplicate_count >= 0),
  non_monotonic_count integer not null default 0 check (non_monotonic_count >= 0),
  stale boolean not null,
  spread_ratio double precision,
  valid boolean not null,
  issues jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists data_quality_symbol_time_idx on public.data_quality_snapshots (symbol, observed_at desc);

create table if not exists public.currency_macro_state (
  id bigint generated by default as identity primary key,
  currency text not null check (char_length(currency) = 3),
  observed_at timestamptz not null,
  rate_score double precision,
  central_bank_score double precision,
  inflation_score double precision,
  growth_score double precision,
  labour_score double precision,
  yield_score double precision,
  risk_score double precision,
  positioning_score double precision,
  macro_score double precision,
  coverage double precision not null check (coverage between 0 and 1),
  freshness_seconds integer not null check (freshness_seconds >= 0),
  evidence jsonb not null default '{}'::jsonb,
  unique (currency, observed_at)
);
create index if not exists currency_macro_state_idx on public.currency_macro_state (currency, observed_at desc);

create table if not exists public.currency_strength (
  id bigint generated by default as identity primary key,
  currency text not null check (char_length(currency) = 3),
  observed_at timestamptz not null,
  strength_15m double precision,
  strength_1h double precision,
  strength_4h double precision,
  strength_1d double precision,
  combined_strength double precision,
  coverage double precision not null check (coverage between 0 and 1),
  unique (currency, observed_at)
);

create table if not exists public.pair_rankings (
  id bigint generated by default as identity primary key,
  run_id uuid references public.scanner_runs(id) on delete cascade,
  observed_at timestamptz not null,
  symbol text not null references public.fx_symbols(symbol),
  direction text check (direction in ('LONG','SHORT','NEUTRAL')),
  macro_edge double precision,
  technical_edge double precision,
  cross_asset_score double precision,
  session_score double precision,
  volatility_score double precision,
  spread_score double precision,
  pair_opportunity_score double precision check (pair_opportunity_score between 0 and 100),
  rank integer check (rank > 0),
  coverage double precision not null check (coverage between 0 and 1),
  created_at timestamptz not null default now()
);
create index if not exists pair_rankings_run_rank_idx on public.pair_rankings (run_id, rank);

create table if not exists public.market_structure (
  id bigint generated by default as identity primary key,
  symbol text not null references public.fx_symbols(symbol),
  timeframe text not null check (timeframe in ('M1','M5','M15','H1','H4','D1')),
  observed_at timestamptz not null,
  trend text,
  last_swing_high double precision,
  last_swing_low double precision,
  bos boolean,
  choch boolean,
  mss boolean,
  premium_discount double precision,
  evidence jsonb not null default '{}'::jsonb,
  unique (symbol, timeframe, observed_at)
);

create table if not exists public.liquidity_levels (
  id bigint generated by default as identity primary key,
  symbol text not null references public.fx_symbols(symbol),
  timeframe text not null,
  observed_at timestamptz not null,
  level double precision not null,
  level_type text not null,
  strength double precision,
  touch_count integer not null default 1 check (touch_count > 0),
  active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb
);
create index if not exists liquidity_active_idx on public.liquidity_levels (symbol, active, observed_at desc);

create table if not exists public.smc_features (
  id bigint generated by default as identity primary key,
  symbol text not null references public.fx_symbols(symbol),
  timeframe text not null,
  observed_at timestamptz not null,
  fvg_type text,
  fvg_low double precision,
  fvg_high double precision,
  order_block_type text,
  ob_low double precision,
  ob_high double precision,
  displacement_score double precision,
  liquidity_sweep boolean,
  sweep_type text,
  evidence jsonb not null default '{}'::jsonb
);

create table if not exists public.signals (
  id uuid primary key default gen_random_uuid(),
  run_id uuid references public.scanner_runs(id) on delete set null,
  observed_at timestamptz not null,
  symbol text not null references public.fx_symbols(symbol),
  direction text not null check (direction in ('LONG','SHORT')),
  setup_type text not null,
  state text not null check (state in ('NO_TRADE','WATCH','SETUP_FORMING','ARMED','EXECUTION_READY','MISSED','INVALIDATED','COOLDOWN')),
  pair_score double precision check (pair_score between 0 and 100),
  execution_score double precision check (execution_score between 0 and 100),
  final_score double precision check (final_score between 0 and 100),
  entry_low double precision,
  entry_high double precision,
  sl double precision,
  tp1 double precision,
  tp2 double precision,
  tp3 double precision,
  rr1 double precision,
  rr2 double precision,
  rr3 double precision,
  macro_bias text,
  h4_bias text,
  h1_bias text,
  active_guards jsonb not null default '[]'::jsonb,
  data_coverage double precision not null check (data_coverage between 0 and 1),
  expires_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists signals_symbol_time_idx on public.signals (symbol, observed_at desc);
create index if not exists signals_state_time_idx on public.signals (state, observed_at desc);

create table if not exists public.paper_trades (
  id uuid primary key default gen_random_uuid(),
  signal_id uuid not null references public.signals(id) on delete restrict,
  entry_time timestamptz not null,
  entry_price double precision not null,
  exit_time timestamptz,
  exit_price double precision,
  spread_cost double precision,
  commission double precision,
  slippage double precision,
  result_r double precision,
  mae_r double precision,
  mfe_r double precision,
  status text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.model_performance (
  id bigint generated by default as identity primary key,
  as_of timestamptz not null,
  setup_type text not null,
  symbol text,
  session text,
  regime text,
  sample_scope text not null,
  trades integer not null check (trades >= 0),
  wins integer not null check (wins >= 0),
  losses integer not null check (losses >= 0),
  win_rate double precision,
  avg_win_r double precision,
  avg_loss_r double precision,
  expectancy_r double precision,
  profit_factor double precision,
  max_drawdown_r double precision,
  metadata jsonb not null default '{}'::jsonb
);

alter table public.fx_symbols enable row level security;
alter table public.scanner_runs enable row level security;
alter table public.data_quality_snapshots enable row level security;
alter table public.currency_macro_state enable row level security;
alter table public.currency_strength enable row level security;
alter table public.pair_rankings enable row level security;
alter table public.market_structure enable row level security;
alter table public.liquidity_levels enable row level security;
alter table public.smc_features enable row level security;
alter table public.signals enable row level security;
alter table public.paper_trades enable row level security;
alter table public.model_performance enable row level security;

revoke all on table public.fx_symbols from anon, authenticated;
revoke all on table public.scanner_runs from anon, authenticated;
revoke all on table public.data_quality_snapshots from anon, authenticated;
revoke all on table public.currency_macro_state from anon, authenticated;
revoke all on table public.currency_strength from anon, authenticated;
revoke all on table public.pair_rankings from anon, authenticated;
revoke all on table public.market_structure from anon, authenticated;
revoke all on table public.liquidity_levels from anon, authenticated;
revoke all on table public.smc_features from anon, authenticated;
revoke all on table public.signals from anon, authenticated;
revoke all on table public.paper_trades from anon, authenticated;
revoke all on table public.model_performance from anon, authenticated;

-- v0.4 mobile/control-plane and broker telemetry.
-- These tables are operational state only; realtime quote/order execution must
-- not synchronously depend on Supabase latency.
create table if not exists public.broker_accounts (
  backend text not null check (backend in ('CTRADER','MT5')),
  account_id text not null,
  broker_name text,
  environment text not null check (environment in ('DEMO','LIVE')),
  enabled boolean not null default false,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (backend, account_id)
);

create table if not exists public.execution_control (
  control_key text primary key default 'primary',
  execution_mode text not null default 'DISABLED'
    check (execution_mode in ('DISABLED','SIMULATION','CONFIRM_TO_TRADE','AUTO')),
  new_orders_enabled boolean not null default false,
  emergency_stop boolean not null default true,
  close_all_requested boolean not null default false,
  version bigint not null default 1,
  updated_at timestamptz not null default now(),
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.runtime_heartbeats (
  worker_name text primary key,
  observed_at timestamptz not null,
  healthy boolean not null,
  lag_seconds double precision,
  details jsonb not null default '{}'::jsonb
);

create table if not exists public.broker_order_events (
  id bigint generated by default as identity primary key,
  observed_at timestamptz not null default now(),
  backend text not null check (backend in ('CTRADER','MT5')),
  account_id text not null,
  signal_key text not null,
  broker_order_id text,
  event_type text not null,
  accepted boolean,
  code text,
  message text,
  payload jsonb not null default '{}'::jsonb
);
create index if not exists broker_order_events_signal_idx
  on public.broker_order_events (signal_key, observed_at desc);

alter table public.broker_accounts enable row level security;
alter table public.execution_control enable row level security;
alter table public.runtime_heartbeats enable row level security;
alter table public.broker_order_events enable row level security;

revoke all on table public.broker_accounts from anon, authenticated;
revoke all on table public.execution_control from anon, authenticated;
revoke all on table public.runtime_heartbeats from anon, authenticated;
revoke all on table public.broker_order_events from anon, authenticated;
