from __future__ import annotations

from datetime import datetime, timezone
from math import isfinite
from typing import Any

from .demo_adaptive_calibration_v2 import SYSTEM_BREAKEVENS, SYSTEM_LOSSES, SYSTEM_WINS
from .demo_outcome_normalization import normalize_adaptive_profit_lock_outcomes
from .storage.supabase_operational import SupabaseOperationalStore

UTC = timezone.utc
STRATEGY_ID = "EURUSD_IMPULSE_RETEST_BASELINE_V1"
# Before this change the active DEMO pipelines were XAUUSD-only, so using the PR
# creation boundary cannot include execution generated by this EURUSD baseline.
STRATEGY_ACTIVATED_NOT_BEFORE = datetime(2026, 9, 10, 23, 14, 11, tzinfo=UTC)
WORKER = "ctrader_demo_eurusd_strategy_forward_scorecard"


def _finite(value: Any) -> float | None:
    try:
        parsed = float(value)
    except (TypeError, ValueError):
        return None
    return parsed if isfinite(parsed) else None


def _stage(decisive: int) -> str:
    if decisive < 5:
        return "OBSERVE"
    if decisive < 10:
        return "SHADOW_COMPARISON_READY"
    if decisive < 20:
        return "MICRO_STRATEGY_REVIEW_ELIGIBLE"
    return "PAIR_SPECIFIC_STRATEGY_REVIEW_ELIGIBLE"


def run() -> int:
    store = SupabaseOperationalStore.from_env()
    signals_response = (
        store.client.table("signals")
        .select("id,observed_at,symbol")
        .eq("symbol", "EURUSD")
        .gte("observed_at", STRATEGY_ACTIVATED_NOT_BEFORE.isoformat())
        .order("observed_at", desc=True)
        .limit(1000)
        .execute()
    )
    signal_ids = {str(row.get("id")) for row in (signals_response.data or []) if row.get("id")}
    closed_response = (
        store.client.table("broker_order_events")
        .select("observed_at,signal_key,code,payload")
        .eq("backend", "CTRADER")
        .eq("event_type", "DEMO_TRADE_CLOSED")
        .order("observed_at", desc=True)
        .limit(500)
        .execute()
    )
    normalized = normalize_adaptive_profit_lock_outcomes(
        store, tuple(dict(row) for row in (closed_response.data or []))
    )

    wins = losses = breakevens = reliable = 0
    net_pnl = 0.0
    for row in normalized:
        payload = row.get("payload") if isinstance(row.get("payload"), dict) else {}
        signal_id = str(row.get("signal_key") or payload.get("signal_id") or "")
        if signal_id not in signal_ids:
            continue
        if str(payload.get("symbol") or "").upper() != "EURUSD":
            continue
        exit_type = str(payload.get("exit_type") or row.get("code") or "").upper()
        if exit_type.startswith("MANUAL_CLOSE_") or bool(payload.get("partial_close", False)):
            continue
        if exit_type not in SYSTEM_WINS | SYSTEM_LOSSES | SYSTEM_BREAKEVENS:
            continue
        reliable += 1
        wins += int(exit_type in SYSTEM_WINS)
        losses += int(exit_type in SYSTEM_LOSSES)
        breakevens += int(exit_type in SYSTEM_BREAKEVENS)
        value = _finite(payload.get("net_pnl_estimate"))
        if value is not None:
            net_pnl += value

    decisive = wins + losses
    win_rate = None if decisive == 0 else wins / decisive
    details = {
        "symbol": "EURUSD",
        "strategy_id": STRATEGY_ID,
        "role": "DEMO_EXECUTION_BASELINE_FOR_PAIR_SPECIFIC_STRATEGY_DISCOVERY",
        "strategy_activated_not_before": STRATEGY_ACTIVATED_NOT_BEFORE.isoformat(),
        "reliable_closed": reliable,
        "decisive": decisive,
        "wins": wins,
        "losses": losses,
        "breakevens": breakevens,
        "win_rate": win_rate,
        "realized_net_pnl": net_pnl,
        "stage": _stage(decisive),
        "minimum_decisive_shadow_comparison": 5,
        "minimum_decisive_micro_strategy_review": 10,
        "minimum_decisive_pair_specific_strategy_review": 20,
        "automatic_strategy_mutation": False,
        "execution_influence": False,
        "live_unlock": False,
        "r_expectancy_status": "NOT_REPORTED_WITHOUT_EXACT_BROKER_RISK_NORMALIZATION",
    }
    store.write_heartbeat(WORKER, healthy=True, lag_seconds=0.0, details=details)
    print(
        "CTRADER_DEMO_EURUSD_FORWARD_SCORECARD "
        f"strategy={STRATEGY_ID} reliable_closed={reliable} decisive={decisive} "
        f"wins={wins} losses={losses} breakevens={breakevens} "
        f"win_rate={'NONE' if win_rate is None else f'{win_rate:.3f}'} "
        f"realized_net={net_pnl:.8g} stage={_stage(decisive)} execution_influence=0"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(run())
