from __future__ import annotations

"""Causal H1 replay harness for the V395 AFIQ-pattern challenger.

V396 intentionally keeps reference prices out of runtime logic. Supply/demand
zones are generated by the existing causal V342 detector, become eligible only
at their recorded ``available_at`` timestamp, and are evaluated with V395 using
information known at each H1 close. Signals fill at the next H1 open.

Primary invalidation follows the V395 policy: two acceptance closes beyond the
structural boundary; a wick alone is not an exit. Results are gross of trading
costs because cTrader trendbars do not provide trustworthy historical spread or
commission. Consequently this replay cannot by itself authorize promotion.
"""

from bisect import bisect_left, bisect_right
from dataclasses import asdict, dataclass
from datetime import timedelta
from math import inf
from statistics import fmean
from typing import Any, Iterable

from .models import ensure_utc
from .xau_afiq_challenger_v395 import MIN_RR, evaluate_afiq_challenger_v395
from .xau_sd_liquidity_engine_v342_legacy import SDZone, TF_PARAMS, detect_zones

CONTRACT = "XAU_RIZAN_AFIQ_CAUSAL_REPLAY_V396"
MAX_HOLD_H1_BARS = 96
MAX_CONTEXT_ZONES = 16
MAX_LIQUIDITY_POINTS = 500


@dataclass(frozen=True, slots=True)
class ZoneReplayMeta:
    zone: SDZone
    available_index: int
    expiry_index: int
    invalidated_index: int | None
    touch_indices: tuple[int, ...]


@dataclass(frozen=True, slots=True)
class ReplayTrade:
    direction: str
    signal_index: int
    entry_index: int
    exit_index: int
    signal_at: str
    entry_at: str
    exit_at: str
    entry: float
    structural_invalidation: float
    target: float
    exit_price: float
    r_multiple: float
    mae_r: float
    mfe_r: float
    bars_held: int
    exit_reason: str
    confirmed_after_entry: bool
    zone_id: str | None
    timeframe: str
    effective_score: float


def _ts(bar: Any):
    return ensure_utc(getattr(bar, "timestamp"))


def _close_at(bar: Any):
    return _ts(bar) + timedelta(hours=1)


def _f(value: Any) -> float:
    return float(value)


def _distance_to_zone(price: float, zone: SDZone) -> float:
    if zone.low <= price <= zone.high:
        return 0.0
    return zone.low - price if price < zone.low else price - zone.high


def build_liquidity_fractals(bars_h1: Iterable[Any]) -> tuple[dict[str, Any], ...]:
    """Create 2-left/2-right H1 pivots with explicit causal availability."""
    bars = tuple(bars_h1)
    out: list[dict[str, Any]] = []
    for i in range(2, len(bars) - 2):
        high = _f(bars[i].high)
        low = _f(bars[i].low)
        left = bars[i - 2 : i]
        right = bars[i + 1 : i + 3]
        available_index = i + 2  # known only after the second right bar closes
        if all(high > _f(x.high) for x in (*left, *right)):
            out.append(
                {
                    "side": "BUY_SIDE",
                    "price": high,
                    "pivot_index": i,
                    "available_index": available_index,
                }
            )
        if all(low < _f(x.low) for x in (*left, *right)):
            out.append(
                {
                    "side": "SELL_SIDE",
                    "price": low,
                    "pivot_index": i,
                    "available_index": available_index,
                }
            )
    return tuple(out)


def build_zone_metadata(zones: Iterable[SDZone], bars_h1: Iterable[Any]) -> tuple[ZoneReplayMeta, ...]:
    """Pre-compute only timestamps/events; all eligibility remains as-of indexed."""
    bars = tuple(bars_h1)
    close_times = [_close_at(bar) for bar in bars]
    metas: list[ZoneReplayMeta] = []
    for zone in zones:
        available_index = bisect_left(close_times, ensure_utc(zone.available_at))
        expiry_at = ensure_utc(zone.available_at) + timedelta(
            hours=float(TF_PARAMS[zone.timeframe]["lifecycle_hours"])
        )
        expiry_index = bisect_left(close_times, expiry_at)
        touch_indices: list[int] = []
        was_inside = False
        invalid_streak = 0
        invalidated_index: int | None = None
        for j in range(max(available_index, 0), len(bars)):
            bar = bars[j]
            inside = _f(bar.high) >= zone.low and _f(bar.low) <= zone.high
            if inside and not was_inside:
                touch_indices.append(j)
            was_inside = inside
            close = _f(bar.close)
            beyond = close < zone.distal if zone.direction == "LONG" else close > zone.distal
            invalid_streak = invalid_streak + 1 if beyond else 0
            if invalid_streak >= 2:
                invalidated_index = j
                break
        metas.append(
            ZoneReplayMeta(
                zone=zone,
                available_index=available_index,
                expiry_index=expiry_index,
                invalidated_index=invalidated_index,
                touch_indices=tuple(touch_indices),
            )
        )
    return tuple(metas)


def _active(meta: ZoneReplayMeta, index: int) -> bool:
    return (
        meta.available_index <= index < meta.expiry_index
        and (meta.invalidated_index is None or index < meta.invalidated_index)
    )


def _known_liquidity(fractals: tuple[dict[str, Any], ...], index: int) -> list[dict[str, Any]]:
    known = [row for row in fractals if int(row["available_index"]) <= index]
    return [dict(row) for row in known[-MAX_LIQUIDITY_POINTS:]]


def _validation_level(direction: str, price: float, liquidity: list[dict[str, Any]]) -> float | None:
    if direction == "LONG":
        levels = [float(row["price"]) for row in liquidity if row["side"] == "BUY_SIDE" and float(row["price"]) > price]
        return min(levels) if levels else None
    levels = [float(row["price"]) for row in liquidity if row["side"] == "SELL_SIDE" and float(row["price"]) < price]
    return max(levels) if levels else None


def _target_for(meta: ZoneReplayMeta, active: list[ZoneReplayMeta], price: float, liquidity: list[dict[str, Any]]) -> float | None:
    direction = meta.zone.direction
    opposing: list[float] = []
    for other in active:
        if other.zone.direction == direction:
            continue
        if direction == "LONG" and other.zone.low > price:
            opposing.append(float(other.zone.low))
        elif direction == "SHORT" and other.zone.high < price:
            opposing.append(float(other.zone.high))
    if opposing:
        return min(opposing) if direction == "LONG" else max(opposing)
    if direction == "LONG":
        fallback = [float(row["price"]) for row in liquidity if row["side"] == "BUY_SIDE" and float(row["price"]) > price]
        return min(fallback) if fallback else None
    fallback = [float(row["price"]) for row in liquidity if row["side"] == "SELL_SIDE" and float(row["price"]) < price]
    return max(fallback) if fallback else None


def build_context(
    bars_h1: tuple[Any, ...],
    metas: tuple[ZoneReplayMeta, ...],
    fractals: tuple[dict[str, Any], ...],
    index: int,
) -> dict[str, Any]:
    """Build the exact V395 context visible at one H1 close."""
    price = _f(bars_h1[index].close)
    active = [meta for meta in metas if _active(meta, index)]
    liquidity = _known_liquidity(fractals, index)
    ranked = sorted(
        active,
        key=lambda meta: (
            _distance_to_zone(price, meta.zone) / max(meta.zone.atr, 1e-9),
            0 if meta.zone.timeframe == "H4" else 1,
        ),
    )[:MAX_CONTEXT_ZONES]

    rows: list[dict[str, Any]] = []
    for meta in ranked:
        zone = meta.zone
        target = _target_for(meta, active, price, liquidity)
        validation = _validation_level(zone.direction, price, liquidity)
        touches = bisect_right(meta.touch_indices, index)
        row = {
            "zone_id": zone.zone_id,
            "direction": zone.direction,
            "timeframe": zone.timeframe,
            "low": float(zone.low),
            "high": float(zone.high),
            "role": "MAIN_REVERSAL_DEMAND" if zone.direction == "LONG" else "MAIN_REVERSAL_SUPPLY",
            "condition": "FRESH" if touches == 0 else "RETEST",
            "strength": 2.0 if zone.structural_bos else 1.25,
            "touch_count": touches,
            "structural_invalidation": float(zone.distal),
            "validation_level": validation,
            "targets": [] if target is None else [float(target)],
            "available_at": ensure_utc(zone.available_at).isoformat(),
        }
        rows.append(row)

    start = max(0, index - 2)
    return {
        "price_now": price,
        "effective_zones": rows,
        "liquidity_candidates": liquidity,
        "acceptance_closes": [float(bars_h1[j].close) for j in range(start, index + 1)],
        "replay_as_of": _close_at(bars_h1[index]).isoformat(),
    }


def _valid_target(direction: str, entry: float, targets: Iterable[Any]) -> float | None:
    values = [float(value) for value in targets]
    if direction == "LONG":
        valid = [value for value in values if value > entry]
        return min(valid) if valid else None
    valid = [value for value in values if value < entry]
    return max(valid) if valid else None


def resolve_trade(
    bars_h1: tuple[Any, ...],
    *,
    signal_index: int,
    candidate: dict[str, Any],
    max_hold: int = MAX_HOLD_H1_BARS,
) -> ReplayTrade | None:
    entry_index = signal_index + 1
    if entry_index >= len(bars_h1):
        return None
    direction = str(candidate["direction"])
    entry = float(bars_h1[entry_index].open)
    stop = float(candidate["structural_invalidation"])
    target = _valid_target(direction, entry, candidate.get("targets") or [])
    if target is None:
        return None
    risk = entry - stop if direction == "LONG" else stop - entry
    reward = target - entry if direction == "LONG" else entry - target
    if risk <= 0 or reward <= 0 or reward / risk < MIN_RR:
        return None

    low = float(candidate["low"])
    high = float(candidate["high"])
    tolerance = 0.25 * max(high - low, 0.01)
    if entry < low - tolerance or entry > high + tolerance:
        return None

    validation = candidate.get("validation_level")
    confirmed = False
    invalid_streak = 0
    mae = 0.0
    mfe = 0.0
    last = min(len(bars_h1) - 1, entry_index + max_hold - 1)
    for j in range(entry_index, last + 1):
        bar = bars_h1[j]
        if direction == "LONG":
            mae = max(mae, entry - float(bar.low))
            mfe = max(mfe, float(bar.high) - entry)
            if validation is not None and float(bar.close) >= float(validation):
                confirmed = True
            beyond = float(bar.close) < stop
            target_hit = float(bar.high) >= target
        else:
            mae = max(mae, float(bar.high) - entry)
            mfe = max(mfe, entry - float(bar.low))
            if validation is not None and float(bar.close) <= float(validation):
                confirmed = True
            beyond = float(bar.close) > stop
            target_hit = float(bar.low) <= target
        invalid_streak = invalid_streak + 1 if beyond else 0

        # Conservative ordering: once acceptance invalidation exists, it wins over
        # a target touched on that same second-confirmation bar.
        if invalid_streak >= 2:
            exit_index = min(j + 1, len(bars_h1) - 1)
            exit_price = float(bars_h1[exit_index].open) if exit_index > j else float(bar.close)
            pnl = exit_price - entry if direction == "LONG" else entry - exit_price
            return ReplayTrade(
                direction=direction,
                signal_index=signal_index,
                entry_index=entry_index,
                exit_index=exit_index,
                signal_at=_close_at(bars_h1[signal_index]).isoformat(),
                entry_at=_ts(bars_h1[entry_index]).isoformat(),
                exit_at=_ts(bars_h1[exit_index]).isoformat(),
                entry=entry,
                structural_invalidation=stop,
                target=target,
                exit_price=exit_price,
                r_multiple=pnl / risk,
                mae_r=mae / risk,
                mfe_r=mfe / risk,
                bars_held=exit_index - entry_index + 1,
                exit_reason="STRUCTURAL_ACCEPTANCE_INVALIDATION",
                confirmed_after_entry=confirmed,
                zone_id=candidate.get("zone_id"),
                timeframe=str(candidate.get("timeframe") or "HTF"),
                effective_score=float(candidate.get("score") or 0.0),
            )
        if target_hit:
            pnl = reward
            return ReplayTrade(
                direction=direction,
                signal_index=signal_index,
                entry_index=entry_index,
                exit_index=j,
                signal_at=_close_at(bars_h1[signal_index]).isoformat(),
                entry_at=_ts(bars_h1[entry_index]).isoformat(),
                exit_at=_ts(bars_h1[j]).isoformat(),
                entry=entry,
                structural_invalidation=stop,
                target=target,
                exit_price=target,
                r_multiple=pnl / risk,
                mae_r=mae / risk,
                mfe_r=mfe / risk,
                bars_held=j - entry_index + 1,
                exit_reason="TARGET",
                confirmed_after_entry=confirmed,
                zone_id=candidate.get("zone_id"),
                timeframe=str(candidate.get("timeframe") or "HTF"),
                effective_score=float(candidate.get("score") or 0.0),
            )

    exit_price = float(bars_h1[last].close)
    pnl = exit_price - entry if direction == "LONG" else entry - exit_price
    return ReplayTrade(
        direction=direction,
        signal_index=signal_index,
        entry_index=entry_index,
        exit_index=last,
        signal_at=_close_at(bars_h1[signal_index]).isoformat(),
        entry_at=_ts(bars_h1[entry_index]).isoformat(),
        exit_at=_close_at(bars_h1[last]).isoformat(),
        entry=entry,
        structural_invalidation=stop,
        target=target,
        exit_price=exit_price,
        r_multiple=pnl / risk,
        mae_r=mae / risk,
        mfe_r=mfe / risk,
        bars_held=last - entry_index + 1,
        exit_reason="TIMEOUT",
        confirmed_after_entry=confirmed,
        zone_id=candidate.get("zone_id"),
        timeframe=str(candidate.get("timeframe") or "HTF"),
        effective_score=float(candidate.get("score") or 0.0),
    )


def _metrics(trades: list[ReplayTrade]) -> dict[str, Any]:
    if not trades:
        return {
            "trades": 0,
            "wins": 0,
            "losses": 0,
            "win_rate": None,
            "gross_profit_factor": None,
            "expectancy_r": None,
            "max_drawdown_r": None,
        }
    rs = [trade.r_multiple for trade in trades]
    positives = [r for r in rs if r > 0]
    negatives = [r for r in rs if r < 0]
    gross_win = sum(positives)
    gross_loss = -sum(negatives)
    equity = 0.0
    peak = 0.0
    max_dd = 0.0
    for r in rs:
        equity += r
        peak = max(peak, equity)
        max_dd = max(max_dd, peak - equity)
    return {
        "trades": len(trades),
        "wins": len(positives),
        "losses": len(negatives),
        "win_rate": len(positives) / len(trades),
        "gross_profit_factor": inf if gross_loss == 0 and gross_win > 0 else (gross_win / gross_loss if gross_loss > 0 else None),
        "expectancy_r": fmean(rs),
        "net_r": sum(rs),
        "max_drawdown_r": max_dd,
        "avg_mae_r": fmean(trade.mae_r for trade in trades),
        "avg_mfe_r": fmean(trade.mfe_r for trade in trades),
        "avg_bars_held": fmean(trade.bars_held for trade in trades),
        "target_hits": sum(trade.exit_reason == "TARGET" for trade in trades),
        "structural_invalidations": sum(trade.exit_reason == "STRUCTURAL_ACCEPTANCE_INVALIDATION" for trade in trades),
        "timeouts": sum(trade.exit_reason == "TIMEOUT" for trade in trades),
        "confirmed_after_entry": sum(trade.confirmed_after_entry for trade in trades),
        "confirmed_rate": sum(trade.confirmed_after_entry for trade in trades) / len(trades),
        "long_trades": sum(trade.direction == "LONG" for trade in trades),
        "short_trades": sum(trade.direction == "SHORT" for trade in trades),
    }


def run_replay(bars_h1: Iterable[Any], bars_h4: Iterable[Any]) -> dict[str, Any]:
    h1 = tuple(sorted(bars_h1, key=lambda bar: _ts(bar)))
    h4 = tuple(sorted(bars_h4, key=lambda bar: _ts(bar)))
    if len(h1) < 200 or len(h4) < 30:
        raise ValueError("V396_REPLAY_INSUFFICIENT_HISTORY")
    as_of = _close_at(h1[-1])
    zones = tuple(detect_zones(h1, timeframe="H1", as_of=as_of)) + tuple(
        detect_zones(h4, timeframe="H4", as_of=as_of)
    )
    metas = build_zone_metadata(zones, h1)
    fractals = build_liquidity_fractals(h1)

    trades: list[ReplayTrade] = []
    state_counts: dict[str, int] = {}
    next_free = 0
    skipped_fill = 0
    for i in range(120, len(h1) - 1):
        if i < next_free:
            continue
        context = build_context(h1, metas, fractals, i)
        result = evaluate_afiq_challenger_v395(context)
        state = str(result.get("state") or "UNKNOWN")
        state_counts[state] = state_counts.get(state, 0) + 1
        if state != "EARLY_TAKE_RISK":
            continue
        candidates = list(result.get("candidates") or [])
        if not candidates:
            continue
        trade = resolve_trade(h1, signal_index=i, candidate=dict(candidates[0]))
        if trade is None:
            skipped_fill += 1
            continue
        trades.append(trade)
        next_free = trade.exit_index + 1

    by_year: dict[str, dict[str, Any]] = {}
    for year in sorted({_ts(h1[trade.entry_index]).year for trade in trades}):
        subset = [trade for trade in trades if _ts(h1[trade.entry_index]).year == year]
        by_year[str(year)] = _metrics(subset)

    metrics = _metrics(trades)
    pf = metrics.get("gross_profit_factor")
    numeric_pf_pass = pf is not None and pf != inf and float(pf) >= 1.5
    if pf == inf:
        numeric_pf_pass = True
    numeric_expectancy_pass = metrics.get("expectancy_r") is not None and float(metrics["expectancy_r"]) > 0
    return {
        "contract": CONTRACT,
        "engine_contract": "XAU_RIZAN_AFIQ_CHALLENGER_V395",
        "bars": {"H1": len(h1), "H4": len(h4)},
        "period": {
            "start": _ts(h1[0]).isoformat(),
            "end": _close_at(h1[-1]).isoformat(),
        },
        "causality": {
            "signal_time": "H1_CLOSE",
            "fill_time": "NEXT_H1_OPEN",
            "zone_availability_enforced": True,
            "fractal_availability_enforced": True,
            "historical_outcomes_not_signal_inputs": True,
            "afiq_reference_prices_used_as_runtime_inputs": False,
            "structural_exit": "TWO_ACCEPTANCE_CLOSES_THEN_NEXT_OPEN",
        },
        "cost_model": "GROSS_ONLY_HISTORICAL_SPREAD_AND_COMMISSION_NOT_AVAILABLE",
        "event_filter": "NOT_APPLIED_NO_CAUSAL_EVENT_ARCHIVE_IN_V396",
        "zones_detected": len(zones),
        "liquidity_fractals": len(fractals),
        "state_counts": state_counts,
        "skipped_next_open_fill_or_rr": skipped_fill,
        "metrics": metrics,
        "by_year": by_year,
        "numeric_gates": {
            "gross_pf_gte_1_5": numeric_pf_pass,
            "expectancy_positive": numeric_expectancy_pass,
        },
        "promotion_eligible": False,
        "promotion_blockers": [
            "GROSS_ONLY_COST_MODEL",
            "CAUSAL_EVENT_BLACKOUT_ARCHIVE_NOT_APPLIED",
            "WALK_FORWARD_REVIEW_REQUIRED",
        ],
        "trades": [asdict(trade) for trade in trades],
    }
